### PR TITLE
docker for binder from root to special dir

### PR DESCRIPTION
**Pull request by NickVeld**
I don't know why week04 commits here, and cannot avoid any redundant commits to perform this change without collaborator status...

### CODE REVIEW

**Comment by NickVeld** [comment]
Please, be careful about the notebook of week04 before and after merging

**Comment by justheuristic** [comment]
Can you confirm that binder works with this location of dockerfile?
We had issues with it last time i checked.

**Comment by NickVeld** [comment]
I do not see any relative reference in the Dockerfile, thus only "docker build" should be called in the right way for the success. After building location does not matter. The parent image cannot depends on the location. 

Building warning:
W: GPG error: http://archive.ubuntu.com trusty-backports InRelease: The followin
g signatures couldn't be verified because the public key is not available: NO_PU
BKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32

Building error:
Could not build doom-py: Command '['make', '-j', '3']' returned non-zero exi
t status 2. (HINT: are you sure cmake is installed? You might also be missing a
library. Try running 'apt-get install -y python-numpy cmake zlib1g-dev libjpeg-d
ev libboost-all-dev gcc libsdl2-dev wget unzip'

And after that

Command "/home/main/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-U8gKYT/doom-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-TTofdS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-U8gKYT/doom-py/
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install ppaquette-gym-doom' returned a non-zero code: 1

My conclusion: Something is changed in ppaquette-gym-doom and it not dockerfile location causes problem.

**Comment by Pastafarianist** [comment]
We cannot merge the PR with the week04 commits. There are two ways around this:

1. Create a new PR. Most likely you will need to pull the `spring19` branch into your fork, then create a new branch based on it (`git checkout spring19 && git checkout -b docker-binder`), [cherry-pick](https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean) the `2198a42` commit onto the new branch (`git cherry-pick 2198a42`), push it to Github (`git push -u origin docker-binder`) and create a new PR from the web interface.
2. Amend the branch you are making the PR from to remove the extra commits. Something like:

```
git remote add main git@github.com:yandexdataschool/Practical_RL
git checkout spring19
git pull main
git checkout patch-10
git reset --hard spring19
git cherry-pick 2198a42
git push --force-with-lease origin
```

**Comment by NickVeld** [comment]
See #151

**Pull request closed without merging**
