### PR TITLE
Update crossentropy_method.ipynb

### PR DESCRIPTION
**Pull request by alexyalunin**
percentile shows the percent of session to be thrown out

### CODE REVIEW

**Comment by dniku** [comment]
Thank you for your contribution! While your change is factually correct, it would be better to write that comment with proper grammar. Can you change it to something like `discard this percentage of sessions with lowest rewards`?

**Review by dniku — CHANGES_REQUESTED** [review]
Needs proper grammar.

**Comment by alexyalunin** [comment]
@dniku sorry, I completely missed this branch, can you finish the changes?

**Comment by dniku** [comment]
OK, I pushed this as a separate commit.

**Pull request closed without merging**
