### PR TITLE
week03: pacman visualization added (#140)

### PR DESCRIPTION
**Pull request by yhn112**
We still have this branch not deleted and not merged. @neer201 could please you look at it and at the discussion in #140? And @dniku, please, remind us what troubles were with it?

### CODE REVIEW

**Comment by NickVeld** [comment]
@yhn112 Why all branches should be merged or deleted. Why the students cannot just use it if they wants taking the thing from this branch? Moreover, why are you do not ask the author (me, and you know how to get me in the ways other than GitHub ) before the deletion. Maybe I have thoughts and I want to do it finally merged. It was said for me that the work on it will be continued. But not just deleted without any notice!

@neer201 I suggested the fully ready-to-merge solution. There is no obstacles, and there is no need to dive in the Pacman. If you do not want to do it at all, let's discuss it and figure out some solution that fits for all. But I think that the two people that are not target audience cannot discuss about the feature existence in the open source development.

@yhn112 , thus if you want to push it forward, encourage discussion about the feature somewhere here with __the students and lecturer(s)__

@justheuristic , please, provide your opinion on it.

**Comment by neer201** [comment]
@NickVeld Stay cool =) All branches should be merged or deleted because we work on a unified and consistent version. It helps to support master and Coursera branches transparently.

I apologize for the voodoo dance. I appreciate your work and @dniku review- it was a long story. As I got, it does not run in Colab and is intended for headless systems which are not popular for this homework assignment. Your suggestion is not presented as instruction with well-defined steps and requirements. Otherwise, the link for this instruction can be placed nearby a bonus task assignment and requires to test it periodically.

**Comment by yhn112** [comment]
@NickVeld just FYI, @neer201 is the one responsible for week 3 tasks. I agree with his opinion whatever it is.

**Comment by NickVeld** [comment]
@neer201 
In my opinion the popular option among hard learners not passers-by is docker usage that helps to overcome colab limitations. The visualization tool is aimed on hard learners thus they can use it.
Of course, I agree to put some additional instructions. Also may be it will be easy to transport output images into jupyter.
I planned to restore the project in memory in July and I would be glad to get feedback, suggestion by this time.

**Pull request closed without merging**
