### PR TITLE
env visualization issue

### PR DESCRIPTION
**Pull request by NickVeld**

### CODE REVIEW

**Comment by Pastafarianist** [comment]
As far as I remember from my testing, `inline` doesn't work well for visualizations which update rapidly. There are certainly issues with this visualization, but replacing `notebook` with `inline` won't fix them.

**Comment by NickVeld** [comment]
> As far as I remember from my testing, `inline` doesn't work well for visualizations which update rapidly. There are certainly issues with this visualization, but replacing `notebook` with `inline` won't fix them.

I remember that some more code stuff is needed for the fix.

**Comment by justheuristic** [comment]
That is correct. The issue was with google colab: the thing just didn't work with 
`%matplotlib notebook`

@Pastafarianist @NickVeld unless there are any suggestions on how to make it run in both jupyter and colab, i'd ask @NickVeld to PR this version as a separate notebook OR as an option in the current one.

**Comment by NickVeld** [comment]
For me this fix works on both Collab and Jupyter (see gif [I hope that it will demonstrate as animatiated gif...]). But I will try to give two options, if it is needed.

**Comment by Pastafarianist** [comment]
@justheuristic I haven't tested this myself, but gifs LGTM.

**Comment by justheuristic** [comment]
LGTM as well. Thank you for contributing!

**Pull request merged**
