### PR TITLE
Fix 'EntryPoints' object has no attribute 'get'

### PR DESCRIPTION
**Pull request by AI-Ahmed**
Error caused by the recent upgrade of the `importlib-metadata`. 4 Oct, 2022.

### CODE REVIEW

**Comment by dniku** [comment]
Hi! Have you made sure that this change fixes the problem?

**Comment by AI-Ahmed** [comment]
> Hi! Have you made sure that this change fixes the problem?

Ofc! I ran the whole notebook before submitting this adjustment!

**Comment by AI-Ahmed** [comment]
Also, I added a reference to my adjustment!

**Comment by dniku** [comment]
Thank you! I've merged your contribution. Much appreciated.

**Comment by AI-Ahmed** [comment]
> Thank you! I've merged your contribution. Much appreciated.

It is my pleasure to contribute to Yandex School!

**Pull request merged**
