### PR TITLE
[Week 3] Improve tips for Q-learning via binarization

### PR DESCRIPTION
**Pull request by dniku**
Fixes https://github.com/yandexdataschool/Practical_RL/issues/200.

### CODE REVIEW

**Comment by dniku** [comment]
Need to review the following threads before declaring the issue solved:

* https://www.coursera.org/learn/practical-rl/discussions/all/threads/RcOWWV_CEei_YA56pmzPTA
* https://www.coursera.org/learn/practical-rl/discussions/all/threads/qNJXx2wOEemjiRJSvqYBEg
* https://www.coursera.org/learn/practical-rl/discussions/all/threads/HQUTOZLSEemiLgpeSTtHXg

**Comment by yhn112** [comment]
My humble opinion, without reading threads, is LGTM

**Comment by dniku** [comment]
Need to make two things more explicit:

1. Coarse binarization (i.e. [1,1,1,1]) works perfectly fine.
2. Annealing epsilon might help.

Also perhaps make histograms more explanatory (currently they don't include any info on what each of the state variables mean)

**Comment by dniku** [comment]
No review for a long time, merging.

**Pull request merged**
